valor = input('Digite algo: ')
print('o tipo desse é:',type(valor))
print('é alfanumérico?',valor.isalnum())
print('é alfabético?',valor.isalpha())
print('é ascii?',valor.isascii())
print('é decimal?',valor.isdecimal())
print('é um digito?',valor.isdigit())
print('é um identificador?',valor.isidentifier())
print('é minúsculo?',valor.islower())
print('é numérico?',valor.isnumeric())
print('é imprimível?',valor.isprintable())
print('é maiúsculo?',valor.isupper())
print('é um titúlo?',valor.istitle())